on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Fmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go code is not formatted."
            exit 1
          else
            echo "Go code is formatted correctly."
          fi
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race ./...
